### PR TITLE
Make breadcrumbs dynamic

### PR DESCRIPTION
**Pull request by tztz**
Hi!

In order that breadcrumbs can change their texts dynamically, e.g. when changing the display language (i18n), also functions should be allowed as breadcrumb value.

This feature is fully backwards compatible. It just adds the means to also use functions as values.
The README is updated as well to reflect sample usage.

### CODE REVIEW

**Comment by tztz** [comment]
Adapted code to your code style.

**Comment by GitScrum** [comment]
@tztz thank you very much, maybe you will be just as interested in this issue #3 ?

**Comment by tztz** [comment]
When do you plan to update the corresponding npm package?

Cheers!

**Comment by GitScrum** [comment]
already)

**Pull request merged**
